-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO network (value) VALUES (E'XRPLEDGER');
--
-- CREATE TABLE "public"."chain_type" ("value" text NOT NULL DEFAULT 'EVM', PRIMARY KEY ("value") );
