const envVars = {
  POSTHOG_KEY: process.env.POSTHOG_KEY,
  SECRET_CENTER: process.env.SECRET_CENTER,
  MONTHLY_PRO_PLAN_CHECKOUT_LINK: process.env.MONTHLY_PRO_PLAN_CHECKOUT_LINK,
  YEARLY_PRO_PLAN_CHECKOUT_LINK: process.env.YEARLY_PRO_PLAN_CHECKOUT_LINK,
  PUBLIC_HASURA_API_URL: process.env.PUBLIC_HASURA_API_URL,
  SECRET_HASURA: process.env.SECRET_HASURA,
  SERVERLESS_API_KEY: process.env.SERVERLESS_API_KEY,
  PUBLIC_FUNCTIONS_URL: process.env.PUBLIC_FUNCTIONS_URL,
  SECRET_ALCHEMY: process.env.SECRET_ALCHEMY,
  SECRET_SUPABASE: process.env.SECRET_SUPABASE,
  PUBLIC_MAGIC_PUBLISHABLE_KEY: process.env.PUBLIC_MAGIC_PUBLISHABLE_KEY,
  NETWORK: process.env.NETWORK,
};

export { envVars };
