packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - "apps/**"
  - "packages/**"
  - "specific-apps/*"
  # if required, exclude some directories
  - "!**/test/**"
  - "!apps/functions/serverless/.gcf_local/**"
  - "!apps/functions/serverless/.serverless-template/**"
