-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO network (value) VALUES (E'XRPLEDGER');
--
-- CREATE TYPE chain_type AS ENUM ('XRP', 'EVM');
