swagger: '2.0'
info:
  version: '1.0.6'
  title: App Creator API
  description: API for creating apps
host: sorcel-api.apigateway.dazzling-botany-406610.cloud.goog
x-google-endpoints:
- name: "sorcel-api.apigateway.dazzling-botany-406610.cloud.goog"
  allowCors: True
basePath: /api
schemes:
  - https
produces:
  - application/json
security:
  - api_key: []
x-google-management:
  metrics:
    - name: 'post-requests'
      displayName: 'post requests'
      valueType: INT64
      metricKind: DELTA
    - name: 'get-requests'
      displayName: 'get requests'
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: 'post-limit'
        metric: 'post-requests'
        unit: '1/min/{project}'
        values:
          STANDARD: 5
      - name: 'get-limit'
        metric: 'get-requests'
        unit: '1/min/{project}'
        values:
          STANDARD: 5
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
