version: 3
endpoint: http://localhost:8080
admin_secret: admin_secret
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
metadata_sources:
- name: dev-3shop
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: postgres://postgres:postgrespassword@postgres:5432/postgres
      isolation_level: read-committed
      use_prepared_statements: false