name: Apply migrations via Hasura

on:
  push:
    branches:
      - dev
      - main

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.base.ref == 'main' && 'production' || 'staging' }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download Hasura CLI
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Apply migrations
        working-directory: apps/api
        run: hasura migrate apply --endpoint ${{ secrets.HASURA_ENDPOINT }} --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }} --database-name dev-3shop
