name: E2E tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      PUBLIC_FUNCTIONS_URL: "https://functions-dev.vercel.app"
      PUBLIC_HASURA_API_URL: "https://smashing-albacore-74.hasura.app/v1/graphql"
      PUBLIC_MAGIC_PUBLISHABLE_KEY: "pk_live_4D8A794EBE593D7D"
      SECRET_ALCHEMY: "x97VSdTdeVeFEUpCDRH1ENsSyi5PYPIP"
      SECRET_HASURA: "nCVvYfVZn0kVQd39iG0OQ2uqbq2G2CLpX6oTLHU9OoHINzFiL5f4CwtzJ0hSRiEI"
      SECRET_MAGIC: "sk_live_23C4458F3EEE6FF9"
      SECRET_SUPABASE: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxanl0Z3hidGV0emV3aXBpa2F4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY2NTczNzc5NSwiZXhwIjoxOTgxMzEzNzk1fQ.913rq_gUqPxJxDK4lYvrrmophNnupbN09LqCp6wUAQ4"
      APP_ID: "b2b579e0-8681-485b-9b5c-332f74edae6b"
      PAPER_CLIENT_ID: "a8a84815-f9dc-4292-8724-850ec225fb90"
      SECRET_POAP: "8SkUED3J4OfpNnYtkF9XmBGLDDkXhXl0TLuM1qDZt1fiaAwJum10u9q9iomDapdNEbfe3YUbVkXrUPNARSxHtCHtVtOsBQfdlljeHKx16SaqUTwalIY5sIszQJwXManD"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn install
    - name: Compile TypeScript files
      run: yarn build:admin
    - name: Run E2E tests
      run: yarn test:e2e:admin
