name: E2E tests

on:
  deployment_status:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.target_url, 'admin')
    env:
      PUBLIC_HASURA_API_URL: "https://smashing-albacore-74.hasura.app/v1/graphql"
      APP_ID: "b2b579e0-8681-485b-9b5c-332f74edae6b"
      SECRET_JWT: "bXYc5pXjGEAjydo8aNO@E1$KUhJl10HA"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Install Playwright
        run: npx playwright install chromium --with-deps
      - name: Run E2E tests
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
          PUBLIC_HASURA_API_URL: ${{ env.PUBLIC_HASURA_API_URL }}
          APP_ID: ${{ env.APP_ID }}
          SECRET_JWT: ${{ env.SECRET_JWT }}
        run: pnpm test:e2e:admin
